### ISSUE TITLE
[Umbrella] Integrate linters and release gates

### ISSUE THREAD

**Issue by navidshaikh** [vmware-tanzu/tanzu-framework#1323]
**Describe the feature request**
This is an umbrella issue tracking integration of linters and release gates via GitHub actions.

- [ ] https://github.com/vmware-tanzu/tanzu-framework/issues/1322
- [ ] https://github.com/vmware-tanzu/tanzu-framework/issues/1320
- [ ] https://github.com/vmware-tanzu/tanzu-framework/issues/1319
- [ ] https://github.com/vmware-tanzu/tanzu-framework/issues/1134

**Additional context**
Team worked on integrating these release gates and linters for TCE, we'd need to port those GitHub actions here.
