### ISSUE TITLE
[Umbrella Issue] TKG Docs required for Oct 4 TCE MVP launch 

### ISSUE THREAD

**Issue by lasomethingsomething** [vmware-tanzu/tanzu-framework#166]
This umbrella issue lists docs required by TKG for the Oct 4 TCE MVP launch. This issue should list any/all docs currently missing from our existing set.

## **MUST-HAVE Community Checklist reqts:**
- [x] Contribution guidelines
   - [x] Should include "how to build from source" as well
- [x]  Common style guide to use for documentation
- [x]  Docs: Have a clear “Getting started” guide for contributors
   - [x] Windows, Mac, and Linux instructions for all client programs
   - [x] Updated Prerequisite/Platform support/compatibility sections
- [x]  Docs: Have a clear “Getting started” guide for users; In review
- [x]  Docs: Ensure that design and architecture documents are available
- [x]  code of conduct
- [X] OWNERS file
- [x] Sample issue templates — [see](https://github.com/vmware-tanzu/tanzu-framework/tree/main/.github/ISSUE_TEMPLATE)
- [x] published roadmap (could be GH project board like GitHub itself, Knative WGs, etc. use?)
- [x] GOVERNANCE directive
- [x] ADOPTERS file 
- [x] Maintainers file like [example](https://github.com/goharbor/community/blob/master/MAINTAINERS.md) or can list them on the project landing page 
- [x]  README
  - [x]  list of features; @iancoffey 
  - [x] include links to relevant outside sources
- [x] Public API should have an accompanying programming guide
- [x] Validate Release Notes Section in case there's been drift (here https://github.com/vmware-tanzu/tanzu-framework/blob/main/docs/release/release-notes-gathering-process.md) cc @vuil 
 - [x] Updated Copyright information 
- [x] Validated external internal links
- [x]  Doc that explains how to select packages/channels, and related language. In staging.
- [x] Doc that includes guidelines for when/what we reject—PRs and issues that are acceptable/will be accepted and not/won't. TCE also creating such a doc: [here](https://github.com/vmware-tanzu/tce/blob/main/CONTRIBUTING.md#contribution-workflow)
