### ISSUE TITLE
Support for fetching package repositories and packages from authenticated registry

### ISSUE THREAD

**Issue by shyaamsn** [vmware-tanzu/tanzu-framework#649]
(This is used to request new product features)

**Describe the feature request**
As a user, I should be able to access all repos/packages that require authentication in private repos.

**Describe alternatives you've considered**
Packages in registry that do not require authentication

**Tasks**
- [x] https://github.com/vmware-tanzu/tanzu-framework/pull/572
- [x] https://github.com/vmware-tanzu/tanzu-framework/pull/579
- [x] #653
- [x] #651
- [x] #758
- [x] #652
- [x] #723

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [x] Addons
- [x] CLI
- [ ] Docs
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [ ] User Experience

**Additional context**
