### ISSUE TITLE
Umbrella Issue: Support multi-AZ deployments of workload clusters on vSphere

### ISSUE THREAD

**Issue by saji-pivotal** [vmware-tanzu/tanzu-framework#863]
**Describe the feature request**
Support workload clusters to be deployed across different ComputeClusters or across different hosts within the same ComputeCluster on vSphere. This will enable clusters to be more resilient. 

**Constituent Issues**
- [x] https://github.com/vmware-tanzu/tanzu-framework/issues/825
- [x] https://github.com/vmware-tanzu/tanzu-framework/issues/827

**Affected product area (please put an X in all that apply)**

- [ ] APIs
- [ ] Addons
- [X] CLI
- [ ] Docs
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [ ] Test and Release
- [X] User Experience

**Additional context**
